os: osx
osx_image: xcode12.2
language: swift
script: xcodebuild clean build test -workspace QuizAppRE.xcworkspace -scheme 'CI' -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=14.4,name=iPhone SE (2nd generation)' ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
